name: letrilandia
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.2.2
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: assets/logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/letrilandia_fondo.png
    - assets/musica.mp3
    - assets/intro.mp3
    - assets/audio/ordenar_abecedario.mp3
    - assets/audio/ordenar_numeros.mp3
    - assets/efecto.mp3
    - assets/fondo_pp1.png
    - assets/fondo_pp2.png
    - assets/audio/
    - assets/creditos_1.png
    - assets/audio/rompecabezas.mp3
    - assets/audio/de_nuevo.mp3
    - assets/audio/numero.mp3
    - assets/audio/seleccionar.mp3
    - assets/audio/a.mp3
    - assets/audio/b.mp3
    - assets/audio/c.mp3
    - assets/audio/d.mp3
    - assets/audio/e.mp3
    - assets/audio/f.mp3
    - assets/audio/g.mp3
    - assets/audio/h.mp3
    - assets/audio/i.mp3
    - assets/audio/j.mp3
    - assets/audio/k.mp3
    - assets/audio/l.mp3
    - assets/audio/m.mp3
    - assets/audio/n.mp3
    - assets/audio/ñ.mp3
    - assets/audio/o.mp3
    - assets/audio/p.mp3
    - assets/audio/q.mp3
    - assets/audio/r.mp3
    - assets/audio/s.mp3
    - assets/audio/t.mp3
    - assets/audio/u.mp3
    - assets/audio/v.mp3
    - assets/audio/w.mp3
    - assets/audio/x.mp3
    - assets/audio/y.mp3
    - assets/audio/z.mp3
    - assets/letras_ingles.mp3
    - assets/numeros_ingles.mp3
    - assets/images/juego_1_icon.png
    - assets/images/juego_2_icon.png
    - assets/images/juego_3_icon.png
    - assets/images/juego_4_icon.png
    - assets/images/juego_5_icon.png
    - assets/images/juego_6_icon.png
    - assets/images/juego_7_icon.png
    - assets/images/juego_8_icon.png
    - assets/images/juego_9_icon.png
    - assets/audio/memorama.mp3
    - assets/audio/dibujar.mp3
    - assets/logo.png
    - assets/rompecabezas/a/a_1.png
    - assets/rompecabezas/a/a_2.png
    - assets/rompecabezas/a/a_3.png
    - assets/rompecabezas/a/a_4.png
    - assets/rompecabezas/a/a.png
    - assets/rompecabezas/b/b_1.png
    - assets/rompecabezas/b/b_2.png
    - assets/rompecabezas/b/b_3.png
    - assets/rompecabezas/b/b_4.png
    - assets/rompecabezas/b/b.png
    - assets/rompecabezas/c/c_1.png
    - assets/rompecabezas/c/c_2.png
    - assets/rompecabezas/c/c_3.png
    - assets/rompecabezas/c/c_4.png
    - assets/rompecabezas/c/c.png
    - assets/rompecabezas/d/d_1.png
    - assets/rompecabezas/d/d_2.png
    - assets/rompecabezas/d/d_3.png
    - assets/rompecabezas/d/d_4.png
    - assets/rompecabezas/d/d.png
    - assets/rompecabezas/e/e_1.png
    - assets/rompecabezas/e/e_2.png
    - assets/rompecabezas/e/e_3.png
    - assets/rompecabezas/e/e_4.png
    - assets/rompecabezas/e/e.png
    - assets/rompecabezas/f/f_1.png
    - assets/rompecabezas/f/f_2.png
    - assets/rompecabezas/f/f_3.png
    - assets/rompecabezas/f/f_4.png
    - assets/rompecabezas/f/f.png
    - assets/rompecabezas/g/g_1.png
    - assets/rompecabezas/g/g_2.png
    - assets/rompecabezas/g/g_3.png
    - assets/rompecabezas/g/g_4.png
    - assets/rompecabezas/g/g.png
    - assets/rompecabezas/h/h_1.png
    - assets/rompecabezas/h/h_2.png
    - assets/rompecabezas/h/h_3.png
    - assets/rompecabezas/h/h_4.png
    - assets/rompecabezas/h/h.png
    - assets/rompecabezas/i/i_1.png
    - assets/rompecabezas/i/i_2.png
    - assets/rompecabezas/i/i_3.png
    - assets/rompecabezas/i/i_4.png
    - assets/rompecabezas/i/i.png
    - assets/rompecabezas/j/j_1.png
    - assets/rompecabezas/j/j_2.png
    - assets/rompecabezas/j/j_3.png
    - assets/rompecabezas/j/j_4.png
    - assets/rompecabezas/j/j.png
    - assets/rompecabezas/k/k_1.png
    - assets/rompecabezas/k/k_2.png
    - assets/rompecabezas/k/k_3.png
    - assets/rompecabezas/k/k_4.png
    - assets/rompecabezas/k/k.png
    - assets/rompecabezas/l/l_1.png
    - assets/rompecabezas/l/l_2.png
    - assets/rompecabezas/l/l_3.png
    - assets/rompecabezas/l/l_4.png
    - assets/rompecabezas/l/l.png
    - assets/rompecabezas/m/m_1.png
    - assets/rompecabezas/m/m_2.png
    - assets/rompecabezas/m/m_3.png
    - assets/rompecabezas/m/m_4.png
    - assets/rompecabezas/m/m.png
    - assets/rompecabezas/n/n_1.png
    - assets/rompecabezas/n/n_2.png
    - assets/rompecabezas/n/n_3.png
    - assets/rompecabezas/n/n_4.png
    - assets/rompecabezas/n/n.png
    - assets/rompecabezas/o/o_1.png
    - assets/rompecabezas/o/o_2.png
    - assets/rompecabezas/o/o_3.png
    - assets/rompecabezas/o/o_4.png
    - assets/rompecabezas/o/o.png
    - assets/rompecabezas/p/p_1.png
    - assets/rompecabezas/p/p_2.png
    - assets/rompecabezas/p/p_3.png
    - assets/rompecabezas/p/p_4.png
    - assets/rompecabezas/p/p.png
    - assets/rompecabezas/q/q_1.png
    - assets/rompecabezas/q/q_2.png
    - assets/rompecabezas/q/q_3.png
    - assets/rompecabezas/q/q_4.png
    - assets/rompecabezas/q/q.png
    - assets/rompecabezas/r/r_1.png
    - assets/rompecabezas/r/r_2.png
    - assets/rompecabezas/r/r_3.png
    - assets/rompecabezas/r/r_4.png
    - assets/rompecabezas/r/r.png
    - assets/rompecabezas/s/s_1.png
    - assets/rompecabezas/s/s_2.png
    - assets/rompecabezas/s/s_3.png
    - assets/rompecabezas/s/s_4.png
    - assets/rompecabezas/s/s.png
    - assets/rompecabezas/t/t_1.png
    - assets/rompecabezas/t/t_2.png
    - assets/rompecabezas/t/t_3.png
    - assets/rompecabezas/t/t_4.png
    - assets/rompecabezas/t/t.png
    - assets/rompecabezas/u/u_1.png
    - assets/rompecabezas/u/u_2.png
    - assets/rompecabezas/u/u_3.png
    - assets/rompecabezas/u/u_4.png
    - assets/rompecabezas/u/u.png
    - assets/rompecabezas/v/v_1.png
    - assets/rompecabezas/v/v_2.png
    - assets/rompecabezas/v/v_3.png
    - assets/rompecabezas/v/v_4.png
    - assets/rompecabezas/v/v.png
    - assets/rompecabezas/w/w_1.png
    - assets/rompecabezas/w/w_2.png
    - assets/rompecabezas/w/w_3.png
    - assets/rompecabezas/w/w_4.png
    - assets/rompecabezas/w/w.png
    - assets/rompecabezas/x/x_1.png
    - assets/rompecabezas/x/x_2.png
    - assets/rompecabezas/x/x_3.png
    - assets/rompecabezas/x/x_4.png
    - assets/rompecabezas/x/x.png
    - assets/rompecabezas/y/y_1.png
    - assets/rompecabezas/y/y_2.png
    - assets/rompecabezas/y/y_3.png
    - assets/rompecabezas/y/y_4.png
    - assets/rompecabezas/y/y.png
    - assets/rompecabezas/z/z_1.png
    - assets/rompecabezas/z/z_2.png
    - assets/rompecabezas/z/z_3.png
    - assets/rompecabezas/z/z_4.png
    - assets/rompecabezas/z/z.png
    - assets/letras/a.png
    - assets/letras/b.png
    - assets/letras/c.png
    - assets/letras/d.png
    - assets/letras/e.png
    - assets/letras/f.png
    - assets/letras/g.png
    - assets/letras/h.png
    - assets/letras/i.png
    - assets/letras/j.png
    - assets/letras/k.png
    - assets/letras/l.png
    - assets/letras/m.png
    - assets/letras/n.png
    - assets/letras/o.png
    - assets/letras/p.png
    - assets/letras/q.png
    - assets/letras/r.png
    - assets/letras/s.png
    - assets/letras/t.png
    - assets/letras/u.png
    - assets/letras/v.png
    - assets/letras/w.png
    - assets/letras/x.png
    - assets/letras/y.png
    - assets/letras/z.png
    - assets/numeros/0.png
    - assets/numeros/1.png
    - assets/numeros/2.png
    - assets/numeros/3.png
    - assets/numeros/4.png
    - assets/numeros/5.png
    - assets/numeros/6.png
    - assets/numeros/7.png
    - assets/numeros/8.png
    - assets/numeros/9.png
    - assets/.env